############################################################
# Dockerfile to build fbcoind container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser fbcoin --disabled-password
USER fbcoin

WORKDIR /home/fbcoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/fbcoin/src
RUN git clone https://github.com/fbcoin-project/fbcoin.git

WORKDIR	/home/fbcoin/src/fbcoin/src
RUN make -f makefile.unix
RUN strip fbcoind
RUN cp -f fbcoind /home/fbcoin/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/fbcoin
RUN mkdir .fbcoin
RUN cp -f src/fbcoin/contrib/docker/fbcoin.conf .fbcoin/

WORKDIR /home/fbcoin/.fbcoin
RUN wget -q https://github.com/fbcoin-project/fbcoin/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/fbcoin
EXPOSE 8332
USER fbcoin
